find_package(OpenMP QUIET)

if (TARGET OpenMP::OpenMP_CXX)
    if (MSFLW_USE_OPENMP)
        message(STATUS "OpenMP available, using it")
        set(MSFL_USE_OPENMP ON)
    else ()
        message(STATUS "OpenMP available but explicitly disabled")
        set(MSFL_USE_OPENMP OFF)
    endif ()
else ()
    message(STATUS "OpenMP is not available.")
    set(MSFL_USE_OPENMP OFF)
endif ()